all: ex01_basicprogram ex02_parameters ex03_pid

ex01_basicprogram: ex01_basicprogram.c
	gcc -o $@ $<

ex02_parameters: ex02_parameters.c
	gcc -o $@ $<

ex03_pid: ex03_pid.c
	gcc -o $@ $<

clean:
	rm -f ex01_basicprogram ex02_parameters ex03_pid
